### ISSUE TITLE
need to adapt coastlines file access to new SDK strucutre

### ISSUE THREAD

**Issue by andreakoelzsch** [movestore/Simple-Raster-Map#2]
OLD: coastlines <- readOGR("ne-coastlines-10m/ne_10m_coastline.shp")

NEW: coastlines <- readOGR(paste0(getAppFilePath(coastlines),"/ne_10m_coastline.shp"))
note: coastlines is the settingsId given in the appspec.json

**Comment by cleemansen** [comment]
The `appspec.json` part to add would be:

```
  "providedAppFiles": [
    {
      "settingId": "coastlines",
      "from": "ne-coastlines-10m"
    }
  ],
```

Note: you don't need to add a new setting with the same ID to the `setting: []` array in `appspec.json` (difficult naming of `settingId`).
